version: "3"
services:
  postgres:
    container_name: postgres
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: golang-testing
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
