CREATE TABLE IF NOT EXISTS User (
    ID SERIAL PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Valid BOOLEAN,
    Username VARCHAR(255),
    Email VARCHAR(255)
);